#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if ./vendor/bin/phpstan exists
if [ -f "./vendor/bin/phpstan" ]; then
    ./vendor/bin/phpstan
else
    echo "PHPStan is not installed."
    exit 1
fi

# Check if ./vendor/bin/pint exists
if [ -f "./vendor/bin/pint" ]; then
    # Formatar cada arquivo alterado usando o Laravel Pint
    STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

    for FILE in $STAGED_FILES; do
        ./vendor/bin/pint "${FILE}" >/dev/null >&1
        git add "${FILE}"
    done
else
    echo "Laravel Pint is not installed."
    exit 1
fi

# Check if ./vendor/bin/pest exists
if [ -f "./vendor/bin/pest" ]; then
    php artisan test --parallel | php
else
    echo "Pest is not installed."
    exit 1
fi

exit 0

